apiVersion: apps/v1
kind: Deployment
metadata:
  name: guacamole-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guacamole
  template:
    metadata:
      labels:
        app: guacamole
    spec:
      containers:
      - name: guacamole-container
        image:  "docker.io/guacamole/guacamole"
        env:
        - name: MYSQL_HOSTNAME
          value: "10.1.0.3"
        - name: GUACD_HOSTNAME
          value: "10.1.0.2"
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: dbenv-secret
              key: MYSQL_DATABASE
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: dbenv-secret
              key: MYSQL_USER
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: dbenv-secret
              key: MYSQL_PASSWORD
        securityContext:
          privileged: true
        ports:
        - containerPort: 8080


---

kind: Service
apiVersion: v1
metadata:
  name: loadbalancer-guaca
spec:
  selector:
    app: guacamole
  ports:
    -  port: 80
       targetPort: 8080
  type: LoadBalancer