name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: guacamole/guacd

    steps:
    - uses: actions/checkout@v4
    - name: autoreconf
      run: autoreconf -if
    - name: configure
      run: ./configure
    - name: make
      run: make
